<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yen Do">

<title>exercise-11</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="exercise-11_files/libs/clipboard/clipboard.min.js"></script>
<script src="exercise-11_files/libs/quarto-html/quarto.js"></script>
<script src="exercise-11_files/libs/quarto-html/popper.min.js"></script>
<script src="exercise-11_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="exercise-11_files/libs/quarto-html/anchor.min.js"></script>
<link href="exercise-11_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="exercise-11_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="exercise-11_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="exercise-11_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="exercise-11_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">exercise-11</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yen Do </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/difiore/ada-datasets/main/Mammal_lifehistories_v2.txt"</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read_tsv</span>(f)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1440 Columns: 14
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (4): order, family, Genus, species
dbl (9): mass(g), gestation(mo), newborn(g), weaning(mo), wean mass(g), AFR(...
num (1): refs

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">d</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">1440</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">14</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">order</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">family</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Genus</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">618</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">species</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1191</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mass(g)</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.835767e+05</td>
<td style="text-align: right;">5.055163e+06</td>
<td style="text-align: right;">-999</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">403.02</td>
<td style="text-align: right;">7009.17</td>
<td style="text-align: right;">1.490000e+08</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">gestation(mo)</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-2.872500e+02</td>
<td style="text-align: right;">4.553600e+02</td>
<td style="text-align: right;">-999</td>
<td style="text-align: right;">-999</td>
<td style="text-align: right;">1.05</td>
<td style="text-align: right;">4.50</td>
<td style="text-align: right;">2.146000e+01</td>
<td style="text-align: left;">▃▁▁▁▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">newborn(g)</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6.703150e+03</td>
<td style="text-align: right;">9.091252e+04</td>
<td style="text-align: right;">-999</td>
<td style="text-align: right;">-999</td>
<td style="text-align: right;">2.65</td>
<td style="text-align: right;">98.00</td>
<td style="text-align: right;">2.250000e+06</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">weaning(mo)</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-4.271700e+02</td>
<td style="text-align: right;">4.967100e+02</td>
<td style="text-align: right;">-999</td>
<td style="text-align: right;">-999</td>
<td style="text-align: right;">0.73</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">4.800000e+01</td>
<td style="text-align: left;">▆▁▁▁▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">wean mass(g)</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.604893e+04</td>
<td style="text-align: right;">5.036502e+05</td>
<td style="text-align: right;">-999</td>
<td style="text-align: right;">-999</td>
<td style="text-align: right;">-999.00</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: right;">1.907500e+07</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">AFR(mo)</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-4.081200e+02</td>
<td style="text-align: right;">5.049700e+02</td>
<td style="text-align: right;">-999</td>
<td style="text-align: right;">-999</td>
<td style="text-align: right;">2.50</td>
<td style="text-align: right;">15.61</td>
<td style="text-align: right;">2.100000e+02</td>
<td style="text-align: left;">▆▁▁▁▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">max. life(mo)</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-4.902600e+02</td>
<td style="text-align: right;">6.153000e+02</td>
<td style="text-align: right;">-999</td>
<td style="text-align: right;">-999</td>
<td style="text-align: right;">-999.00</td>
<td style="text-align: right;">147.25</td>
<td style="text-align: right;">1.368000e+03</td>
<td style="text-align: left;">▇▁▅▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">litter size</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-5.563000e+01</td>
<td style="text-align: right;">2.348800e+02</td>
<td style="text-align: right;">-999</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.27</td>
<td style="text-align: right;">3.84</td>
<td style="text-align: right;">1.418000e+01</td>
<td style="text-align: left;">▁▁▁▁▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">litters/year</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-4.771400e+02</td>
<td style="text-align: right;">5.000300e+02</td>
<td style="text-align: right;">-999</td>
<td style="text-align: right;">-999</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">1.15</td>
<td style="text-align: right;">7.500000e+00</td>
<td style="text-align: left;">▇▁▁▁▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">refs</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.054762e+12</td>
<td style="text-align: right;">3.619709e+13</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">116</td>
<td style="text-align: right;">1229.00</td>
<td style="text-align: right;">1242249.75</td>
<td style="text-align: right;">1.368101e+15</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Categorical variables: order, family, genus, species. Numeric variables: mass(g), gestation(mo), newborn(g), weaning(mo), wean mass(g), AFR(mo), max. life(mo), litter size, litters/year, refs.</p>
<section id="step-1-replace-all-values-of--999-the-authors-code-for-missing-data-with-na." class="level3">
<h3 class="anchored" data-anchor-id="step-1-replace-all-values-of--999-the-authors-code-for-missing-data-with-na.">Step 1: Replace all values of -999 (the authors’ code for missing data) with NA.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'naniar'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:skimr':

    n_complete</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">replace_with_na_all</span>(<span class="at">data =</span> d, <span class="at">condition =</span> <span class="sc">~</span>.x <span class="sc">==</span> <span class="sc">-</span><span class="dv">999</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,440 × 14
   order        family      Genus species `mass(g)` `gestation(mo)` `newborn(g)`
   &lt;chr&gt;        &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt;       &lt;dbl&gt;           &lt;dbl&gt;        &lt;dbl&gt;
 1 Artiodactyla Antilocapr… Anti… americ…    45375             8.13        3246.
 2 Artiodactyla Bovidae     Addax nasoma…   182375             9.39        5480 
 3 Artiodactyla Bovidae     Aepy… melamp…    41480             6.35        5093 
 4 Artiodactyla Bovidae     Alce… busela…   150000             7.9        10167.
 5 Artiodactyla Bovidae     Ammo… clarkei    28500             6.8           NA 
 6 Artiodactyla Bovidae     Ammo… lervia     55500             5.08        3810 
 7 Artiodactyla Bovidae     Anti… marsup…    30000             5.72        3910 
 8 Artiodactyla Bovidae     Anti… cervic…    37500             5.5         3846 
 9 Artiodactyla Bovidae     Bison bison     497667.            8.93       20000 
10 Artiodactyla Bovidae     Bison bonasus   500000             9.14       23000.
# ℹ 1,430 more rows
# ℹ 7 more variables: `weaning(mo)` &lt;dbl&gt;, `wean mass(g)` &lt;dbl&gt;,
#   `AFR(mo)` &lt;dbl&gt;, `max. life(mo)` &lt;dbl&gt;, `litter size` &lt;dbl&gt;,
#   `litters/year` &lt;dbl&gt;, refs &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="step-2-drop-the-variables-litter-size-and-refs." class="level3">
<h3 class="anchored" data-anchor-id="step-2-drop-the-variables-litter-size-and-refs.">Step 2: Drop the variables litter size and refs.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> d <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span><span class="st">"litter size"</span>, <span class="sc">-</span> <span class="st">"refs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-3-log-transform-all-of-the-other-numeric-variables." class="level3">
<h3 class="anchored" data-anchor-id="step-3-log-transform-all-of-the-other-numeric-variables.">Step 3: Log transform all of the other numeric variables.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> d <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), log))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There were 8 warnings in `mutate()`.
The first warning was:
ℹ In argument: `across(where(is.numeric), log)`.
Caused by warning:
! NaNs produced
ℹ Run `dplyr::last_dplyr_warnings()` to see the 7 remaining warnings.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 12
  order        family       Genus species `mass(g)` `gestation(mo)` `newborn(g)`
  &lt;chr&gt;        &lt;chr&gt;        &lt;chr&gt; &lt;chr&gt;       &lt;dbl&gt;           &lt;dbl&gt;        &lt;dbl&gt;
1 Artiodactyla Antilocapri… Anti… americ…      10.7            2.10         8.09
2 Artiodactyla Bovidae      Addax nasoma…      12.1            2.24         8.61
3 Artiodactyla Bovidae      Aepy… melamp…      10.6            1.85         8.54
4 Artiodactyla Bovidae      Alce… busela…      11.9            2.07         9.23
5 Artiodactyla Bovidae      Ammo… clarkei      10.3            1.92       NaN   
6 Artiodactyla Bovidae      Ammo… lervia       10.9            1.63         8.25
# ℹ 5 more variables: `weaning(mo)` &lt;dbl&gt;, `wean mass(g)` &lt;dbl&gt;,
#   `AFR(mo)` &lt;dbl&gt;, `max. life(mo)` &lt;dbl&gt;, `litters/year` &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="step-4-regression" class="level3">
<h3 class="anchored" data-anchor-id="step-4-regression">Step 4: Regression</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>relGest <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">`</span><span class="at">gestation(mo)</span><span class="st">`</span> <span class="sc">~</span> <span class="st">`</span><span class="at">mass(g)</span><span class="st">`</span>, <span class="at">data =</span> d, <span class="at">na.action=</span>na.exclude)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>relWean <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">`</span><span class="at">weaning(mo)</span><span class="st">`</span> <span class="sc">~</span> <span class="st">`</span><span class="at">mass(g)</span><span class="st">`</span>, <span class="at">data =</span> d, <span class="at">na.action=</span>na.exclude)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>relAFR <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">`</span><span class="at">AFR(mo)</span><span class="st">`</span> <span class="sc">~</span> <span class="st">`</span><span class="at">mass(g)</span><span class="st">`</span>, <span class="at">data =</span> d, <span class="at">na.action=</span>na.exclude)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>relLife <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">`</span><span class="at">max. life(mo)</span><span class="st">`</span> <span class="sc">~</span> <span class="st">`</span><span class="at">mass(g)</span><span class="st">`</span>, <span class="at">data =</span> d, <span class="at">na.action=</span>na.exclude)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>relNewbornMass <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">`</span><span class="at">newborn(g)</span><span class="st">`</span> <span class="sc">~</span> <span class="st">`</span><span class="at">mass(g)</span><span class="st">`</span>, <span class="at">data =</span> d, <span class="at">na.action=</span>na.exclude)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>relWeaningMass <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">`</span><span class="at">wean mass(g)</span><span class="st">`</span> <span class="sc">~</span> <span class="st">`</span><span class="at">mass(g)</span><span class="st">`</span>, <span class="at">data =</span> d, <span class="at">na.action=</span>na.exclude)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> d <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">relGest =</span> <span class="fu">residuals</span>(relGest),</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">relWean =</span> <span class="fu">residuals</span>(relWean),</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>                 <span class="at">relAFR =</span> <span class="fu">residuals</span>(relAFR),</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>                 <span class="at">relLife =</span> <span class="fu">residuals</span>(relLife),</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>                 <span class="at">relNewbornMass =</span> <span class="fu">residuals</span>(relNewbornMass),</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>                 <span class="at">relWeaningMass =</span> <span class="fu">residuals</span>(relWeaningMass))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-5-plot-residuals" class="level3">
<h3 class="anchored" data-anchor-id="step-5-plot-residuals">Step 5: Plot residuals</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot helper function</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>plot_residuals <span class="ot">&lt;-</span> <span class="cf">function</span>(resid_col, title) {</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> order, <span class="at">y =</span> .data[[resid_col]])) <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> title, <span class="at">y =</span> <span class="st">"Residual"</span>, <span class="at">x =</span> <span class="st">"Order"</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_residuals</span>(<span class="st">"relLife"</span>, <span class="st">"Residual Max Lifespan by Order"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 848 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exercise-11_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_residuals</span>(<span class="st">"relNewbornMass"</span>, <span class="st">"Residual Newborn Mass by Order"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 624 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exercise-11_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_residuals</span>(<span class="st">"relWeaningMass"</span>, <span class="st">"Residual Weaning Mass by Order"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1044 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exercise-11_files/figure-html/unnamed-chunk-6-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Which mammalian orders have the highest residual lifespan?</p>
<p>Primates have the highest residual lifespan.</p>
<p>Which mammalian orders have the have highest residual newborn mass?</p>
<p>Macroscelidea have highest residual newborn mass.</p>
<p>Which mammalian orders have the have highest residual weaning mass?</p>
<p>Perissodactya have the have highest residual weaning mass.</p>
</section>
<section id="step-6-model" class="level3">
<h3 class="anchored" data-anchor-id="step-6-model">Step 6: Model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    select</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AICcmodavg)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MuMIn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MuMIn'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:AICcmodavg':

    AICc, DIC, importance</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select variables for model</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>d1 <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(<span class="st">`</span><span class="at">max. life(mo)</span><span class="st">`</span>, <span class="st">`</span><span class="at">gestation(mo)</span><span class="st">`</span>, <span class="st">`</span><span class="at">newborn(g)</span><span class="st">`</span>,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>          <span class="st">`</span><span class="at">weaning(mo)</span><span class="st">`</span>, <span class="st">`</span><span class="at">wean mass(g)</span><span class="st">`</span>, <span class="st">`</span><span class="at">litters/year</span><span class="st">`</span>, <span class="st">`</span><span class="at">mass(g)</span><span class="st">`</span>, <span class="st">`</span><span class="at">AFR(mo)</span><span class="st">`</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Full model</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>m_max_life <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">`</span><span class="at">max. life(mo)</span><span class="st">`</span> <span class="sc">~</span> <span class="st">`</span><span class="at">gestation(mo)</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">newborn(g)</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>                   <span class="st">`</span><span class="at">weaning(mo)</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">wean mass(g)</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>                   <span class="st">`</span><span class="at">litters/year</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">mass(g)</span><span class="st">`</span>, <span class="at">data =</span> d1, <span class="at">na.action =</span> <span class="st">"na.fail"</span>)</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>m_AFR <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="st">`</span><span class="at">AFR(mo)</span><span class="st">`</span> <span class="sc">~</span> <span class="st">`</span><span class="at">gestation(mo)</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">newborn(g)</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>                   <span class="st">`</span><span class="at">weaning(mo)</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">wean mass(g)</span><span class="st">`</span> <span class="sc">+</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>                   <span class="st">`</span><span class="at">litters/year</span><span class="st">`</span> <span class="sc">+</span> <span class="st">`</span><span class="at">mass(g)</span><span class="st">`</span>, <span class="at">data =</span> d1, <span class="at">na.action =</span> <span class="st">"na.fail"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="model-for-max.-life-mo" class="level4">
<h4 class="anchored" data-anchor-id="model-for-max.-life-mo">Model for max. life (mo)</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model for max. life(mo)</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>mods_life <span class="ot">&lt;-</span> <span class="fu">dredge</span>(m_max_life, <span class="at">beta =</span> <span class="st">"none"</span>, <span class="at">m.lim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Fixed term is "(Intercept)"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># best model</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>mods_life[<span class="dv">1</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Global model call: lm(formula = `max. life(mo)` ~ `gestation(mo)` + `newborn(g)` + 
    `weaning(mo)` + `wean mass(g)` + `litters/year` + `mass(g)`, 
    data = d1, na.action = "na.fail")
---
Model selection table 
   (Int) `gst(mo)` `ltt/yer` `mss(g)` `wnn(mo)` df   logLik  AICc delta weight
40 4.032    0.2953   -0.2525  0.08226    0.1416  6 -122.206 256.8     0      1
Models ranked by AICc(x) </code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of models have delta AIC &lt; 4</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(mods_life<span class="sc">$</span>delta <span class="sc">&lt;</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate and plot the model-averaged coefficients and their CIs for max_life(mo)</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>(mods.list_life <span class="ot">&lt;-</span> <span class="fu">get.models</span>(mods_life, <span class="at">subset =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`40`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `litters/year` + 
    `mass(g)` + `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`        `mass(g)`  
        4.03241          0.29528         -0.25252          0.08226  
  `weaning(mo)`  
        0.14159  


$`52`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `litters/year` + 
    `wean mass(g)` + `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`   `wean mass(g)`  
        4.13286          0.28473         -0.26917          0.08586  
  `weaning(mo)`  
        0.13506  


$`16`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `litters/year` + 
    `mass(g)` + `newborn(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`        `mass(g)`  
        3.98315          0.47997         -0.32926          0.13269  
   `newborn(g)`  
       -0.08198  


$`8`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `litters/year` + 
    `mass(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`        `mass(g)`  
         4.1709           0.3876          -0.3687           0.0722  


$`44`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `litters/year` + 
    `newborn(g)` + `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`     `newborn(g)`  
        4.34453          0.26011         -0.30875          0.07974  
  `weaning(mo)`  
        0.14641  


$`24`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `litters/year` + 
    `mass(g)` + `wean mass(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`        `mass(g)`  
       4.167202         0.392239        -0.368517         0.080180  
 `wean mass(g)`  
      -0.009642  


$`20`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `litters/year` + 
    `wean mass(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`   `wean mass(g)`  
        4.25402          0.37460         -0.37865          0.07578  


$`46`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `mass(g)` + 
    `newborn(g)` + `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`        `mass(g)`     `newborn(g)`  
        3.60022          0.39347          0.16149         -0.08463  
  `weaning(mo)`  
        0.20727  


$`28`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `litters/year` + 
    `newborn(g)` + `wean mass(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`     `newborn(g)`  
         4.1369           0.4279          -0.3498          -0.0663  
 `wean mass(g)`  
         0.1321  


$`38`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `mass(g)` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`        `mass(g)`    `weaning(mo)`  
         3.7471           0.2846           0.1024           0.2357  


$`54`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `mass(g)` + 
    `wean mass(g)` + `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`        `mass(g)`   `wean mass(g)`  
        3.74184          0.29139          0.11424         -0.01432  
  `weaning(mo)`  
        0.23571  


$`12`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `litters/year` + 
    `newborn(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`     `newborn(g)`  
        4.46192          0.38152         -0.42275          0.06221  


$`47`

Call:
lm(formula = `max. life(mo)` ~ `litters/year` + `mass(g)` + `newborn(g)` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`       `mass(g)`    `newborn(g)`   `weaning(mo)`  
       4.03797        -0.26539         0.06403         0.07591         0.22565  


$`50`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `wean mass(g)` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `wean mass(g)`    `weaning(mo)`  
         3.8508           0.2706           0.1085           0.2353  


$`43`

Call:
lm(formula = `max. life(mo)` ~ `litters/year` + `newborn(g)` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`    `newborn(g)`   `weaning(mo)`  
        4.2762         -0.3044          0.1349          0.2193  


$`59`

Call:
lm(formula = `max. life(mo)` ~ `litters/year` + `newborn(g)` + 
    `wean mass(g)` + `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`    `newborn(g)`  `wean mass(g)`   `weaning(mo)`  
       4.11347        -0.27607         0.07593         0.06638         0.21705  


$`58`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `newborn(g)` + 
    `wean mass(g)` + `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`     `newborn(g)`   `wean mass(g)`  
        3.76825          0.33311         -0.06357          0.16015  
  `weaning(mo)`  
        0.21395  


$`51`

Call:
lm(formula = `max. life(mo)` ~ `litters/year` + `wean mass(g)` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`  `wean mass(g)`   `weaning(mo)`  
        3.9487         -0.2546          0.1448          0.2201  


$`39`

Call:
lm(formula = `max. life(mo)` ~ `litters/year` + `mass(g)` + `weaning(mo)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`       `mass(g)`   `weaning(mo)`  
        3.8071         -0.2383          0.1366          0.2410  


$`55`

Call:
lm(formula = `max. life(mo)` ~ `litters/year` + `mass(g)` + `wean mass(g)` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`       `mass(g)`  `wean mass(g)`   `weaning(mo)`  
       3.86510        -0.24175         0.06638         0.07676         0.22832  


$`36`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `litters/year` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`    `weaning(mo)`  
        4.52214          0.51639         -0.36138          0.09754  


$`4`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `litters/year` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`  
         4.5785           0.5632          -0.4350  


$`37`

Call:
lm(formula = `max. life(mo)` ~ `mass(g)` + `weaning(mo)` + 1, 
    data = d1, na.action = "na.fail")

Coefficients:
  (Intercept)      `mass(g)`  `weaning(mo)`  
       3.5450         0.1538         0.3267  


$`45`

Call:
lm(formula = `max. life(mo)` ~ `mass(g)` + `newborn(g)` + `weaning(mo)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
  (Intercept)      `mass(g)`   `newborn(g)`  `weaning(mo)`  
      3.68607        0.10427        0.05324        0.32270  


$`42`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `newborn(g)` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`     `newborn(g)`    `weaning(mo)`  
        4.08348          0.25240          0.09984          0.26778  


$`53`

Call:
lm(formula = `max. life(mo)` ~ `mass(g)` + `wean mass(g)` + `weaning(mo)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)       `mass(g)`  `wean mass(g)`   `weaning(mo)`  
       3.59514         0.08914         0.07093         0.31606  


$`49`

Call:
lm(formula = `max. life(mo)` ~ `wean mass(g)` + `weaning(mo)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `wean mass(g)`   `weaning(mo)`  
        3.6898          0.1635          0.3112  


$`61`

Call:
lm(formula = `max. life(mo)` ~ `mass(g)` + `newborn(g)` + `wean mass(g)` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)       `mass(g)`    `newborn(g)`  `wean mass(g)`   `weaning(mo)`  
       3.67537         0.08297         0.03912         0.03777         0.31810  


$`57`

Call:
lm(formula = `max. life(mo)` ~ `newborn(g)` + `wean mass(g)` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)    `newborn(g)`  `wean mass(g)`   `weaning(mo)`  
       3.78125         0.04857         0.11439         0.31417  


$`14`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `mass(g)` + 
    `newborn(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`        `mass(g)`     `newborn(g)`  
         3.4690           0.6601           0.2182          -0.1679  


$`30`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `mass(g)` + 
    `newborn(g)` + `wean mass(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`        `mass(g)`     `newborn(g)`  
        3.44960          0.64619          0.16228         -0.19865  
 `wean mass(g)`  
        0.09375  


$`41`

Call:
lm(formula = `max. life(mo)` ~ `newborn(g)` + `weaning(mo)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
  (Intercept)   `newborn(g)`  `weaning(mo)`  
       4.0207         0.1531         0.3368  


$`26`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `newborn(g)` + 
    `wean mass(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`     `newborn(g)`   `wean mass(g)`  
         3.6520           0.5916          -0.1626           0.2389  


$`11`

Call:
lm(formula = `max. life(mo)` ~ `litters/year` + `newborn(g)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`    `newborn(g)`  
        4.4430         -0.5228          0.1509  


$`27`

Call:
lm(formula = `max. life(mo)` ~ `litters/year` + `newborn(g)` + 
    `wean mass(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`    `newborn(g)`  `wean mass(g)`  
       4.25823        -0.48852         0.08448         0.07459  


$`15`

Call:
lm(formula = `max. life(mo)` ~ `litters/year` + `mass(g)` + `newborn(g)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`       `mass(g)`    `newborn(g)`  
       4.26720        -0.49824         0.04823         0.10685  


$`19`

Call:
lm(formula = `max. life(mo)` ~ `litters/year` + `wean mass(g)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`  `wean mass(g)`  
        4.0769         -0.4680          0.1621  


$`31`

Call:
lm(formula = `max. life(mo)` ~ `litters/year` + `mass(g)` + `newborn(g)` + 
    `wean mass(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`       `mass(g)`    `newborn(g)`  `wean mass(g)`  
       4.23668        -0.48696         0.01466         0.08255         0.06172  


$`6`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `mass(g)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`        `mass(g)`  
         3.7647           0.4944           0.1005  


$`23`

Call:
lm(formula = `max. life(mo)` ~ `litters/year` + `mass(g)` + `wean mass(g)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`       `mass(g)`  `wean mass(g)`  
       4.04207        -0.46579         0.02931         0.13233  


$`22`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `mass(g)` + 
    `wean mass(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`        `mass(g)`   `wean mass(g)`  
        3.75910          0.50152          0.11301         -0.01513  


$`34`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `weaning(mo)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`    `weaning(mo)`  
         4.2576           0.5860           0.2309  


$`7`

Call:
lm(formula = `max. life(mo)` ~ `litters/year` + `mass(g)` + 1, 
    data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`       `mass(g)`  
        3.9556         -0.4821          0.1518  


$`18`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `wean mass(g)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `wean mass(g)`  
         3.8669           0.4807           0.1064  


$`10`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + `newborn(g)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`     `newborn(g)`  
         4.1388           0.5649           0.0732  


$`2`

Call:
lm(formula = `max. life(mo)` ~ `gestation(mo)` + 1, data = d1, 
    na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`  
          4.266            0.786  


$`17`

Call:
lm(formula = `max. life(mo)` ~ `wean mass(g)` + 1, data = d1, 
    na.action = "na.fail")

Coefficients:
   (Intercept)  `wean mass(g)`  
         3.498           0.235  


$`21`

Call:
lm(formula = `max. life(mo)` ~ `mass(g)` + `wean mass(g)` + 1, 
    data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)       `mass(g)`  `wean mass(g)`  
       3.43774         0.05476         0.17880  


$`25`

Call:
lm(formula = `max. life(mo)` ~ `newborn(g)` + `wean mass(g)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)    `newborn(g)`  `wean mass(g)`  
       3.53642         0.02097         0.21408  


$`29`

Call:
lm(formula = `max. life(mo)` ~ `mass(g)` + `newborn(g)` + `wean mass(g)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)       `mass(g)`    `newborn(g)`  `wean mass(g)`  
       3.46768         0.05234         0.01479         0.16653  


$`13`

Call:
lm(formula = `max. life(mo)` ~ `mass(g)` + `newborn(g)` + 1, 
    data = d1, na.action = "na.fail")

Coefficients:
 (Intercept)     `mass(g)`  `newborn(g)`  
     3.50341       0.14908       0.07862  


$`5`

Call:
lm(formula = `max. life(mo)` ~ `mass(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
(Intercept)    `mass(g)`  
     3.2905       0.2235  


$`9`

Call:
lm(formula = `max. life(mo)` ~ `newborn(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
 (Intercept)  `newborn(g)`  
      3.9794        0.2258  


$`35`

Call:
lm(formula = `max. life(mo)` ~ `litters/year` + `weaning(mo)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`   `weaning(mo)`  
        4.8622         -0.5613          0.3410  


$`3`

Call:
lm(formula = `max. life(mo)` ~ `litters/year` + 1, data = d1, 
    na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`  
        5.2558         -0.9758  


$`33`

Call:
lm(formula = `max. life(mo)` ~ `weaning(mo)` + 1, data = d1, 
    na.action = "na.fail")

Coefficients:
  (Intercept)  `weaning(mo)`  
       4.4952         0.6199  


$`1`

Call:
lm(formula = `max. life(mo)` ~ 1, data = d1, na.action = "na.fail")

Coefficients:
(Intercept)  
      5.058  


attr(,"rank")
function (x) 
do.call("rank", list(x))
&lt;environment: 0x1187178e8&gt;
attr(,"call")
AICc(x)
attr(,"class")
[1] "function"     "rankFunction"
attr(,"beta")
[1] "none"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mods_life)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept) `gestation(mo)` `litters/year`  `mass(g)` `weaning(mo)`
40    4.032412       0.2952754     -0.2525193 0.08226121    0.14159144
52    4.132862       0.2847333     -0.2691681         NA    0.13506030
16    3.983147       0.4799683     -0.3292647 0.13268588            NA
8     4.170950       0.3876414     -0.3686750 0.07220230            NA
44    4.344534       0.2601086     -0.3087459         NA    0.14640907
24    4.167202       0.3922393     -0.3685168 0.08018049            NA
20    4.254018       0.3745994     -0.3786488         NA            NA
46    3.600221       0.3934726             NA 0.16149446    0.20727247
28    4.136892       0.4279325     -0.3497932         NA            NA
38    3.747149       0.2846067             NA 0.10240714    0.23573924
54    3.741842       0.2913915             NA 0.11424192    0.23571464
12    4.461923       0.3815220     -0.4227540         NA            NA
47    4.037970              NA     -0.2653854 0.06402910    0.22564564
50    3.850804       0.2706490             NA         NA    0.23532559
43    4.276221              NA     -0.3043986         NA    0.21926110
59    4.113472              NA     -0.2760696         NA    0.21704568
58    3.768255       0.3331091             NA         NA    0.21394989
51    3.948667              NA     -0.2546133         NA    0.22011139
39    3.807105              NA     -0.2383495 0.13661054    0.24102627
55    3.865103              NA     -0.2417503 0.06638349    0.22832002
36    4.522138       0.5163918     -0.3613799         NA    0.09753556
4     4.578462       0.5631729     -0.4350265         NA            NA
37    3.545002              NA             NA 0.15380735    0.32667362
45    3.686073              NA             NA 0.10426863    0.32269986
42    4.083477       0.2523956             NA         NA    0.26778141
53    3.595142              NA             NA 0.08913668    0.31606098
49    3.689787              NA             NA         NA    0.31121914
61    3.675366              NA             NA 0.08296534    0.31810194
57    3.781254              NA             NA         NA    0.31416930
14    3.468993       0.6601144             NA 0.21819336            NA
30    3.449605       0.6461900             NA 0.16227629            NA
41    4.020731              NA             NA         NA    0.33684371
26    3.652041       0.5915999             NA         NA            NA
11    4.443008              NA     -0.5228320         NA            NA
27    4.258230              NA     -0.4885183         NA            NA
15    4.267203              NA     -0.4982363 0.04822993            NA
19    4.076853              NA     -0.4679517         NA            NA
31    4.236681              NA     -0.4869640 0.01466053            NA
6     3.764709       0.4943793             NA 0.10050742            NA
23    4.042070              NA     -0.4657853 0.02930813            NA
22    3.759100       0.5015240             NA 0.11301042            NA
34    4.257609       0.5859659             NA         NA    0.23091102
7     3.955577              NA     -0.4820727 0.15175506            NA
18    3.866861       0.4806616             NA         NA            NA
10    4.138807       0.5649195             NA         NA            NA
2     4.265537       0.7860422             NA         NA            NA
17    3.497722              NA             NA         NA            NA
21    3.437742              NA             NA 0.05476005            NA
25    3.536420              NA             NA         NA            NA
29    3.467681              NA             NA 0.05234354            NA
13    3.503409              NA             NA 0.14907618            NA
5     3.290512              NA             NA 0.22348389            NA
9     3.979399              NA             NA         NA            NA
35    4.862228              NA     -0.5612883         NA    0.34096754
3     5.255826              NA     -0.9757693         NA            NA
33    4.495178              NA             NA         NA    0.61985016
1     5.057762              NA             NA         NA            NA
   `wean mass(g)` `newborn(g)`
40             NA           NA
52    0.085856390           NA
16             NA  -0.08197905
8              NA           NA
44             NA   0.07974367
24   -0.009641536           NA
20    0.075775571           NA
46             NA  -0.08463126
28    0.132139624  -0.06630393
38             NA           NA
54   -0.014324243           NA
12             NA   0.06221179
47             NA   0.07590705
50    0.108543440           NA
43             NA   0.13490697
59    0.066380025   0.07593117
58    0.160150316  -0.06356866
51    0.144755718           NA
39             NA           NA
55    0.076755339           NA
36             NA           NA
4              NA           NA
37             NA           NA
45             NA   0.05323935
42             NA   0.09984414
53    0.070930277           NA
49    0.163510257           NA
61    0.037773195   0.03912162
57    0.114386103   0.04857142
14             NA  -0.16791063
30    0.093752662  -0.19864794
41             NA   0.15311929
26    0.238874783  -0.16255424
11             NA   0.15093604
27    0.074592051   0.08448220
15             NA   0.10684591
19    0.162062263           NA
31    0.061718324   0.08254922
6              NA           NA
23    0.132325227           NA
22   -0.015132767           NA
34             NA           NA
7              NA           NA
18    0.106413918           NA
10             NA   0.07319658
2              NA           NA
17    0.234989001           NA
21    0.178796771           NA
25    0.214075981   0.02096691
29    0.166527543   0.01478694
13             NA   0.07862096
5              NA           NA
9              NA   0.22578486
35             NA           NA
3              NA           NA
33             NA           NA
1              NA           NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>(mods.avg_life <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">model.avg</span>(mods_life, <span class="at">subset =</span> delta <span class="sc">&lt;</span> <span class="dv">4</span>, <span class="at">fit =</span> <span class="cn">TRUE</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
model.avg(object = get.models(object = mods_life, subset = delta &lt; 
    4))

Component model call: 
lm(formula = `max. life(mo)` ~ &lt;2 unique rhs&gt;, data = d1, na.action = 
     na.fail)

Component models: 
     df  logLik   AICc delta weight
1235  6 -122.21 256.83  0.00   0.81
1245  6 -123.63 259.69  2.85   0.19

Term codes: 
`gestation(mo)`  `litters/year`       `mass(g)`  `wean mass(g)`   `weaning(mo)` 
              1               2               3               4               5 

Model-averaged coefficients:  
(full average) 
                Estimate Std. Error Adjusted SE z value Pr(&gt;|z|)    
(Intercept)      4.05185    0.13639     0.13715  29.544  &lt; 2e-16 ***
`gestation(mo)`  0.29324    0.07370     0.07415   3.955 7.66e-05 ***
`litters/year`  -0.25574    0.07750     0.07797   3.280  0.00104 ** 
`mass(g)`        0.06634    0.03669     0.03674   1.806  0.07094 .  
`weaning(mo)`    0.14033    0.05218     0.05249   2.673  0.00751 ** 
`wean mass(g)`   0.01661    0.03522     0.03524   0.471  0.63732    
 
(conditional average) 
                Estimate Std. Error Adjusted SE z value Pr(&gt;|z|)    
(Intercept)      4.05185    0.13639     0.13715  29.544  &lt; 2e-16 ***
`gestation(mo)`  0.29324    0.07370     0.07415   3.955 7.66e-05 ***
`litters/year`  -0.25574    0.07750     0.07797   3.280  0.00104 ** 
`mass(g)`        0.08226    0.01897     0.01908   4.311 1.62e-05 ***
`weaning(mo)`    0.14033    0.05218     0.05249   2.673  0.00751 ** 
`wean mass(g)`   0.08586    0.02161     0.02174   3.949 7.83e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mods.avg_life)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      2.5 %     97.5 %
(Intercept)      3.78304344  4.3206545
`gestation(mo)`  0.14790552  0.4385654
`litters/year`  -0.40855582 -0.1029259
`mass(g)`        0.04486373  0.1196587
`weaning(mo)`    0.03744025  0.2432151
`wean mass(g)`   0.04324855  0.1284642</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mods.avg_life, <span class="at">full =</span> <span class="cn">TRUE</span>, <span class="at">intercept =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exercise-11_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Best model (model 40): max. life(mo) ~ gestation(mo) + weaning(mo) + litters/year + mass(g)</p>
<p>2 models have delta AICc &lt; 4</p>
<p>Model-averaged coefficients: Mammals with longer gestation, weaning period, or higher mass tend to live longer.</p>
<p>wean mass(g) is also positively associated, though its effect is smaller.</p>
<p>litters/year is negatively associated — species with more litters per year tend to have shorter maximum lifespans (consistent with a “fast” life history strategy).</p>
</section>
<section id="model-for-afrmo" class="level4">
<h4 class="anchored" data-anchor-id="model-for-afrmo">Model for AFR(mo)</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>mods_AFR <span class="ot">&lt;-</span> <span class="fu">dredge</span>(m_AFR, <span class="at">beta =</span> <span class="st">"none"</span>, <span class="at">m.lim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Fixed term is "(Intercept)"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># best model</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>mods_AFR[<span class="dv">1</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Global model call: lm(formula = `AFR(mo)` ~ `gestation(mo)` + `newborn(g)` + `weaning(mo)` + 
    `wean mass(g)` + `litters/year` + `mass(g)`, data = d1, na.action = "na.fail")
---
Model selection table 
   (Int) `gst(mo)` `ltt/yer` `mss(g)` `wnn(mo)` df   logLik  AICc delta weight
40 1.973     0.403   -0.7097  0.03619    0.1447  6 -154.402 321.2     0      1
Models ranked by AICc(x) </code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of models have delta AIC &lt; 4</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(mods_AFR<span class="sc">$</span>delta <span class="sc">&lt;</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate and plot the model-averaged coefficients and their CIs for AFR(mo)</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>(mods.list_AFR <span class="ot">&lt;-</span> <span class="fu">get.models</span>(mods_AFR, <span class="at">subset =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`40`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `litters/year` + `mass(g)` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`        `mass(g)`  
        1.97319          0.40296         -0.70968          0.03619  
  `weaning(mo)`  
        0.14467  


$`52`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `litters/year` + `wean mass(g)` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`   `wean mass(g)`  
        2.01331          0.39590         -0.71604          0.03867  
  `weaning(mo)`  
        0.14219  


$`36`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `litters/year` + `weaning(mo)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`    `weaning(mo)`  
         2.1886           0.5002          -0.7576           0.1253  


$`44`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `litters/year` + `newborn(g)` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`     `newborn(g)`  
        2.10049          0.37305         -0.73145          0.03957  
  `weaning(mo)`  
        0.14954  


$`4`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `litters/year` + 1, 
    data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`  
         2.2610           0.5603          -0.8522  


$`8`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `litters/year` + `mass(g)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`        `mass(g)`  
        2.11474          0.49734         -0.82836          0.02591  


$`20`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `litters/year` + `wean mass(g)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`   `wean mass(g)`  
        2.14086          0.49051         -0.83130          0.02805  


$`12`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `litters/year` + `newborn(g)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`     `newborn(g)`  
        2.22039          0.49707         -0.84790          0.02167  


$`16`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `litters/year` + `mass(g)` + 
    `newborn(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`        `mass(g)`  
        2.03972          0.53422         -0.81262          0.05007  
   `newborn(g)`  
       -0.03275  


$`28`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `litters/year` + `newborn(g)` + 
    `wean mass(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`     `newborn(g)`  
        2.08355          0.51661         -0.81718         -0.03244  
 `wean mass(g)`  
        0.05563  


$`24`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `litters/year` + `mass(g)` + 
    `wean mass(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `litters/year`        `mass(g)`  
       2.116221         0.495518        -0.828424         0.022754  
 `wean mass(g)`  
       0.003815  


$`43`

Call:
lm(formula = `AFR(mo)` ~ `litters/year` + `newborn(g)` + `weaning(mo)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`    `newborn(g)`   `weaning(mo)`  
        2.0025         -0.7252          0.1187          0.2540  


$`47`

Call:
lm(formula = `AFR(mo)` ~ `litters/year` + `mass(g)` + `newborn(g)` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`       `mass(g)`    `newborn(g)`   `weaning(mo)`  
       2.10048        -0.74126        -0.02633         0.14295         0.25140  


$`59`

Call:
lm(formula = `AFR(mo)` ~ `litters/year` + `newborn(g)` + `wean mass(g)` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`    `newborn(g)`  `wean mass(g)`   `weaning(mo)`  
       2.06009        -0.73524         0.13955        -0.02348         0.25481  


$`51`

Call:
lm(formula = `AFR(mo)` ~ `litters/year` + `wean mass(g)` + `weaning(mo)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`  `wean mass(g)`   `weaning(mo)`  
        1.7572         -0.6958          0.1206          0.2604  


$`55`

Call:
lm(formula = `AFR(mo)` ~ `litters/year` + `mass(g)` + `wean mass(g)` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`       `mass(g)`  `wean mass(g)`   `weaning(mo)`  
     1.7561959      -0.6956479       0.0007948       0.1197489       0.2605459  


$`39`

Call:
lm(formula = `AFR(mo)` ~ `litters/year` + `mass(g)` + `weaning(mo)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`       `mass(g)`   `weaning(mo)`  
        1.6657         -0.6903          0.1104          0.2804  


$`11`

Call:
lm(formula = `AFR(mo)` ~ `litters/year` + `newborn(g)` + 1, data = d1, 
    na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`    `newborn(g)`  
        2.1957         -0.9783          0.1373  


$`15`

Call:
lm(formula = `AFR(mo)` ~ `litters/year` + `mass(g)` + `newborn(g)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`       `mass(g)`    `newborn(g)`  
       2.35588        -1.00069        -0.04393         0.17742  


$`27`

Call:
lm(formula = `AFR(mo)` ~ `litters/year` + `newborn(g)` + `wean mass(g)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`    `newborn(g)`  `wean mass(g)`  
       2.23003        -0.98465         0.14959        -0.01384  


$`31`

Call:
lm(formula = `AFR(mo)` ~ `litters/year` + `mass(g)` + `newborn(g)` + 
    `wean mass(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`       `mass(g)`    `newborn(g)`  `wean mass(g)`  
       2.33247        -0.99204        -0.06969         0.15878         0.04735  


$`19`

Call:
lm(formula = `AFR(mo)` ~ `litters/year` + `wean mass(g)` + 1, 
    data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`  `wean mass(g)`  
        1.9089         -0.9482          0.1410  


$`23`

Call:
lm(formula = `AFR(mo)` ~ `litters/year` + `mass(g)` + `wean mass(g)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`       `mass(g)`  `wean mass(g)`  
       1.95814        -0.95130        -0.04151         0.18316  


$`7`

Call:
lm(formula = `AFR(mo)` ~ `litters/year` + `mass(g)` + 1, data = d1, 
    na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`       `mass(g)`  
        1.8384         -0.9738          0.1280  


$`38`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `mass(g)` + `weaning(mo)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`        `mass(g)`    `weaning(mo)`  
        1.17149          0.37298          0.09281          0.40926  


$`46`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `mass(g)` + `newborn(g)` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`        `mass(g)`     `newborn(g)`  
        1.01012          0.49254          0.15770         -0.09295  
  `weaning(mo)`  
        0.37800  


$`50`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `wean mass(g)` + `weaning(mo)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `wean mass(g)`    `weaning(mo)`  
        1.26298          0.35843          0.09902          0.40892  


$`54`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `mass(g)` + `wean mass(g)` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`        `mass(g)`   `wean mass(g)`  
       1.168846         0.376354         0.098694        -0.007126  
  `weaning(mo)`  
       0.409251  


$`58`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `newborn(g)` + `wean mass(g)` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`     `newborn(g)`   `wean mass(g)`  
        1.15824          0.43769         -0.08066          0.16450  
  `weaning(mo)`  
        0.38179  


$`35`

Call:
lm(formula = `AFR(mo)` ~ `litters/year` + `weaning(mo)` + 1, 
    data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`   `weaning(mo)`  
        2.5181         -0.9512          0.3611  


$`42`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `newborn(g)` + `weaning(mo)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`     `newborn(g)`    `weaning(mo)`  
        1.48202          0.35478          0.08719          0.43709  


$`49`

Call:
lm(formula = `AFR(mo)` ~ `wean mass(g)` + `weaning(mo)` + 1, 
    data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `wean mass(g)`   `weaning(mo)`  
        1.0497          0.1718          0.5094  


$`45`

Call:
lm(formula = `AFR(mo)` ~ `mass(g)` + `newborn(g)` + `weaning(mo)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
  (Intercept)      `mass(g)`   `newborn(g)`  `weaning(mo)`  
      1.11759        0.08607        0.07964        0.52249  


$`37`

Call:
lm(formula = `AFR(mo)` ~ `mass(g)` + `weaning(mo)` + 1, data = d1, 
    na.action = "na.fail")

Coefficients:
  (Intercept)      `mass(g)`  `weaning(mo)`  
       0.9066         0.1602         0.5284  


$`57`

Call:
lm(formula = `AFR(mo)` ~ `newborn(g)` + `wean mass(g)` + `weaning(mo)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)    `newborn(g)`  `wean mass(g)`   `weaning(mo)`  
       1.17532         0.06669         0.10437         0.51348  


$`34`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `weaning(mo)` + 1, 
    data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`    `weaning(mo)`  
         1.6341           0.6461           0.4049  


$`53`

Call:
lm(formula = `AFR(mo)` ~ `mass(g)` + `wean mass(g)` + `weaning(mo)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)       `mass(g)`  `wean mass(g)`   `weaning(mo)`  
       0.97937         0.06627         0.10299         0.51302  


$`41`

Call:
lm(formula = `AFR(mo)` ~ `newborn(g)` + `weaning(mo)` + 1, data = d1, 
    na.action = "na.fail")

Coefficients:
  (Intercept)   `newborn(g)`  `weaning(mo)`  
       1.3938         0.1621         0.5342  


$`61`

Call:
lm(formula = `AFR(mo)` ~ `mass(g)` + `newborn(g)` + `wean mass(g)` + 
    `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)       `mass(g)`    `newborn(g)`  `wean mass(g)`   `weaning(mo)`  
       1.10286         0.05677         0.06022         0.05195         0.51617  


$`30`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `mass(g)` + `newborn(g)` + 
    `wean mass(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`        `mass(g)`     `newborn(g)`  
         0.7391           0.9561           0.1697          -0.2950  
 `wean mass(g)`  
         0.1532  


$`14`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `mass(g)` + `newborn(g)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`        `mass(g)`     `newborn(g)`  
         0.7708           0.9788           0.2611          -0.2448  


$`26`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `newborn(g)` + `wean mass(g)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`     `newborn(g)`   `wean mass(g)`  
         0.9509           0.8990          -0.2573           0.3050  


$`3`

Call:
lm(formula = `AFR(mo)` ~ `litters/year` + 1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `litters/year`  
         2.935          -1.390  


$`6`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `mass(g)` + 1, data = d1, 
    na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`        `mass(g)`  
        1.20197          0.73716          0.08951  


$`18`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `wean mass(g)` + 1, 
    data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`   `wean mass(g)`  
        1.29088          0.72336          0.09532  


$`22`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `mass(g)` + `wean mass(g)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`        `mass(g)`   `wean mass(g)`  
        1.19881          0.74119          0.09656         -0.00853  


$`2`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`  
         1.6480           0.9969  


$`10`

Call:
lm(formula = `AFR(mo)` ~ `gestation(mo)` + `newborn(g)` + 1, 
    data = d1, na.action = "na.fail")

Coefficients:
    (Intercept)  `gestation(mo)`     `newborn(g)`  
         1.5723           0.8649           0.0437  


$`33`

Call:
lm(formula = `AFR(mo)` ~ `weaning(mo)` + 1, data = d1, na.action = "na.fail")

Coefficients:
  (Intercept)  `weaning(mo)`  
       1.8960         0.8337  


$`17`

Call:
lm(formula = `AFR(mo)` ~ `wean mass(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)  `wean mass(g)`  
        0.7353          0.2888  


$`25`

Call:
lm(formula = `AFR(mo)` ~ `newborn(g)` + `wean mass(g)` + 1, data = d1, 
    na.action = "na.fail")

Coefficients:
   (Intercept)    `newborn(g)`  `wean mass(g)`  
       0.77516         0.02157         0.26730  


$`21`

Call:
lm(formula = `AFR(mo)` ~ `mass(g)` + `wean mass(g)` + 1, data = d1, 
    na.action = "na.fail")

Coefficients:
   (Intercept)       `mass(g)`  `wean mass(g)`  
       0.72388         0.01047         0.27807  


$`29`

Call:
lm(formula = `AFR(mo)` ~ `mass(g)` + `newborn(g)` + `wean mass(g)` + 
    1, data = d1, na.action = "na.fail")

Coefficients:
   (Intercept)       `mass(g)`    `newborn(g)`  `wean mass(g)`  
       0.76586         0.00708         0.02073         0.26087  


$`13`

Call:
lm(formula = `AFR(mo)` ~ `mass(g)` + `newborn(g)` + 1, data = d1, 
    na.action = "na.fail")

Coefficients:
 (Intercept)     `mass(g)`  `newborn(g)`  
      0.8218        0.1586        0.1207  


$`5`

Call:
lm(formula = `AFR(mo)` ~ `mass(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
(Intercept)    `mass(g)`  
     0.4949       0.2729  


$`9`

Call:
lm(formula = `AFR(mo)` ~ `newborn(g)` + 1, data = d1, na.action = "na.fail")

Coefficients:
 (Intercept)  `newborn(g)`  
      1.3283        0.2773  


$`1`

Call:
lm(formula = `AFR(mo)` ~ 1, data = d1, na.action = "na.fail")

Coefficients:
(Intercept)  
      2.653  


attr(,"rank")
function (x) 
do.call("rank", list(x))
&lt;environment: 0x11e1608c8&gt;
attr(,"call")
AICc(x)
attr(,"class")
[1] "function"     "rankFunction"
attr(,"beta")
[1] "none"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mods_AFR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept) `gestation(mo)` `litters/year`     `mass(g)` `weaning(mo)`
40   1.9731875       0.4029622     -0.7096797  0.0361881443     0.1446707
52   2.0133060       0.3959018     -0.7160394            NA     0.1421900
36   2.1886266       0.5002352     -0.7575694            NA     0.1252897
44   2.1004901       0.3730539     -0.7314495            NA     0.1495434
4    2.2609783       0.5603281     -0.8521723            NA            NA
8    2.1147387       0.4973370     -0.8283615  0.0259104829            NA
20   2.1408581       0.4905119     -0.8312994            NA            NA
12   2.2203925       0.4970665     -0.8478983            NA            NA
16   2.0397228       0.5342159     -0.8126195  0.0500699458            NA
28   2.0835533       0.5166054     -0.8171816            NA            NA
24   2.1162214       0.4955178     -0.8284241  0.0227538382            NA
43   2.0025144              NA     -0.7252146            NA     0.2540295
47   2.1004833              NA     -0.7412569 -0.0263287775     0.2514041
59   2.0600872              NA     -0.7352360            NA     0.2548132
51   1.7571964              NA     -0.6958019            NA     0.2604476
55   1.7561959              NA     -0.6956479  0.0007948417     0.2605459
39   1.6657120              NA     -0.6903421  0.1103586646     0.2803694
11   2.1957483              NA     -0.9782852            NA            NA
15   2.3558844              NA     -1.0006888 -0.0439315000            NA
27   2.2300349              NA     -0.9846523            NA            NA
31   2.3324665              NA     -0.9920402 -0.0696874323            NA
19   1.9088724              NA     -0.9482353            NA            NA
23   1.9581406              NA     -0.9513039 -0.0415134591            NA
7    1.8384184              NA     -0.9738487  0.1279752527            NA
38   1.1714857       0.3729792             NA  0.0928062081     0.4092635
46   1.0101193       0.4925434             NA  0.1577001033     0.3779992
50   1.2629777       0.3584348             NA            NA     0.4089151
54   1.1688459       0.3763543             NA  0.0986935320     0.4092512
58   1.1582356       0.4376871             NA            NA     0.3817926
35   2.5180758              NA     -0.9512232            NA     0.3611054
42   1.4820213       0.3547810             NA            NA     0.4370865
49   1.0497349              NA             NA            NA     0.5094250
45   1.1175873              NA             NA  0.0860656310     0.5224896
37   0.9065709              NA             NA  0.1601665603     0.5284336
57   1.1753157              NA             NA            NA     0.5134755
34   1.6340892       0.6460852             NA            NA     0.4048879
53   0.9793714              NA             NA  0.0662682025     0.5130246
41   1.3938214              NA             NA            NA     0.5341642
61   1.1028627              NA             NA  0.0567684773     0.5161663
30   0.7391188       0.9560601             NA  0.1697294428            NA
14   0.7708011       0.9788135             NA  0.2611009103            NA
26   0.9508534       0.8989629             NA            NA            NA
3    2.9349209              NA     -1.3901837            NA            NA
6    1.2019708       0.7371623             NA  0.0895081410            NA
18   1.2908799       0.7233646             NA            NA            NA
22   1.1988098       0.7411893             NA  0.0965553887            NA
2    1.6479898       0.9969064             NA            NA            NA
10   1.5723336       0.8648986             NA            NA            NA
33   1.8960325              NA             NA            NA     0.8337316
17   0.7353494              NA             NA            NA            NA
25   0.7751610              NA             NA            NA            NA
21   0.7238828              NA             NA  0.0104686626            NA
29   0.7658631              NA             NA  0.0070801801            NA
13   0.8218330              NA             NA  0.1586143872            NA
5    0.4949028              NA             NA  0.2728766816            NA
9    1.3282776              NA             NA            NA            NA
1    2.6527377              NA             NA            NA            NA
   `wean mass(g)` `newborn(g)`
40             NA           NA
52    0.038667637           NA
36             NA           NA
44             NA   0.03957305
4              NA           NA
8              NA           NA
20    0.028054664           NA
12             NA   0.02166584
16             NA  -0.03274558
28    0.055631133  -0.03243962
24    0.003814764           NA
43             NA   0.11868956
47             NA   0.14295033
59   -0.023481990   0.13955230
51    0.120563055           NA
55    0.119748854           NA
39             NA           NA
11             NA   0.13726036
15             NA   0.17742101
27   -0.013841012   0.14959127
31    0.047353035   0.15877951
19    0.141041086           NA
23    0.183162065           NA
7              NA           NA
38             NA           NA
46             NA  -0.09294805
50    0.099019596           NA
54   -0.007125728           NA
58    0.164500774  -0.08065884
35             NA           NA
42             NA   0.08719304
49    0.171815073           NA
45             NA   0.07963640
37             NA           NA
57    0.104369106   0.06668708
34             NA           NA
53    0.102986965           NA
41             NA   0.16207951
61    0.051947239   0.06022112
30    0.153196836  -0.29504962
14             NA  -0.24482322
26    0.304984239  -0.25729817
3              NA           NA
6              NA           NA
18    0.095319217           NA
22   -0.008529500           NA
2              NA           NA
10             NA   0.04369754
33             NA           NA
17    0.288816415           NA
25    0.267301338   0.02157052
21    0.278073958           NA
29    0.260869761   0.02073459
13             NA   0.12073225
5              NA           NA
9              NA   0.27731201
1              NA           NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>(mods.avg_AFR <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">model.avg</span>(mods_AFR, <span class="at">subset =</span> delta <span class="sc">&lt;</span> <span class="dv">4</span>, <span class="at">fit =</span> <span class="cn">TRUE</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
model.avg(object = get.models(object = mods_AFR, subset = delta &lt; 
    4))

Component model call: 
lm(formula = `AFR(mo)` ~ &lt;7 unique rhs&gt;, data = d1, na.action = 
     na.fail)

Component models: 
     df  logLik   AICc delta weight
1236  6 -154.40 321.23  0.00   0.26
1256  6 -154.55 321.52  0.30   0.22
126   5 -155.76 321.82  0.59   0.19
1246  6 -154.70 321.82  0.59   0.19
12    4 -157.96 324.12  2.89   0.06
123   5 -157.26 324.81  3.58   0.04
125   5 -157.32 324.94  3.71   0.04

Term codes: 
`gestation(mo)`  `litters/year`       `mass(g)`    `newborn(g)`  `wean mass(g)` 
              1               2               3               4               5 
  `weaning(mo)` 
              6 

Model-averaged coefficients:  
(full average) 
                 Estimate Std. Error Adjusted SE z value Pr(&gt;|z|)    
(Intercept)      2.077348   0.155135    0.155747  13.338  &lt; 2e-16 ***
`gestation(mo)`  0.431246   0.102802    0.103227   4.178 2.95e-05 ***
`litters/year`  -0.742844   0.096772    0.097242   7.639  &lt; 2e-16 ***
`mass(g)`        0.010362   0.020067    0.020111   0.515    0.606    
`weaning(mo)`    0.120698   0.075321    0.075576   1.597    0.110    
`wean mass(g)`   0.009658   0.020793    0.020841   0.463    0.643    
`newborn(g)`     0.007523   0.019607    0.019651   0.383    0.702    
 
(conditional average) 
                Estimate Std. Error Adjusted SE z value Pr(&gt;|z|)    
(Intercept)      2.07735    0.15513     0.15575  13.338  &lt; 2e-16 ***
`gestation(mo)`  0.43125    0.10280     0.10323   4.178 2.95e-05 ***
`litters/year`  -0.74284    0.09677     0.09724   7.639  &lt; 2e-16 ***
`mass(g)`        0.03472    0.02244     0.02257   1.538   0.1240    
`weaning(mo)`    0.14080    0.06154     0.06190   2.275   0.0229 *  
`wean mass(g)`   0.03704    0.02538     0.02553   1.451   0.1468    
`newborn(g)`     0.03957    0.02746     0.02763   1.432   0.1520    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mods.avg_AFR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       2.5 %      97.5 %
(Intercept)      1.772090289  2.38260614
`gestation(mo)`  0.228924250  0.63356700
`litters/year`  -0.933435667 -0.55225257
`mass(g)`       -0.009518041  0.07895965
`weaning(mo)`    0.019474192  0.26213558
`wean mass(g)`  -0.012989579  0.08706876
`newborn(g)`    -0.014572450  0.09371854</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mods.avg_AFR, <span class="at">full =</span> <span class="cn">TRUE</span>, <span class="at">intercept =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exercise-11_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Best model (AICc = 321.23): AFR(mo) ~ gestation(mo) + weaning(mo) + litters/year + mass(g)</p>
<p>7 models have delta AICc &lt; 4</p>
<p>Model-averaged coefficients:</p>
<p>Longer gestation → later reproduction</p>
<p>Fewer litters per year → later reproduction</p>
<p>Longer weaning duration also has a smaller but significant effect.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>